### PR TITLE
I got this error

### PR DESCRIPTION
**Pull request by iraitc**
array_key_exists(): The first argument should be either a string or an integer.
when  changed to string then error disappeared .

### CODE REVIEW

**Comment by RoumenDamianoff** [comment]
What version are you using? Because this change breaks the package for Laravel 5.2.

**Comment by arcanedev-maroc** [comment]
I agree with @RoumenDamianoff, the `--tag` must be an array for L5.2

**Comment by iraitc** [comment]
Hi , I'm Using laravel 5.0

**Comment by iraitc** [comment]
excuse me , my version is  5.0.3 
I think we should set this condition

if(version_compare(app()->version(),'5.0.33')<=0) {  // for  (smaller) versions
 // call with tag as string parameter
} else{
 // call with tag as array parameter
}

**Pull request merged**
