### PR TITLE
Update SitemapServiceProvider.php

### PR DESCRIPTION
**Pull request by iraitc**
it copies vendor files to "public" folder and makes the issue because my public folder is "public_html"

### CODE REVIEW

**Comment by iraitc** [comment]
It was big issue , why you didn't approve it !?

**Comment by RoumenDamianoff** [comment]
Are you serious? Did you see what your PR looks like? Look again and you will see why.

**Comment by iraitc** [comment]
OH , your are sure , it was my mistake , I will send PR again .

**Comment by iraitc** [comment]
I saw you have fixed it , thanks .  fixed issue [#94](https://github.com/RoumenDamianoff/laravel-sitemap/commit/94e2f21aa9a0bef4c7b4883369e35e42f1be60ee)

**Pull request closed without merging**
